version: '3'
services:
  reearth:
    image: dschiffer12/geo-forge:latest
    environment:
      REEARTH_DB: mongodb+srv://dschiffer12:Goose1212@geoforge-serverless.hbcn0se.mongodb.net/?retryWrites=true&w=majority
    ports:
      - 8080:8080
    # env_file:
    #  - ./.env
    links:
      - reearth-mongo
    depends_on:
      - reearth-mongo
    volumes:
      - ./data:/reearth/data
  reearth-mongo:
    image: mongo:5-focal
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
